Add support for Buffer secrets (#214)
fastify/fastify-cookie pull request #215
Opened 2022-09-19 15:41 UTC by pluma

Fixes #214.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-09-19 15:55 UTC, mcollina approved these changes
lgtm

2022-09-20 12:35 UTC, jsumners commented on signer.js
> +    if (typeof secret !== 'string' && !Buffer.isBuffer(secret)) {
```suggestion
    if (typeof secret !== 'string' && Buffer.isBuffer(secret) === false) {
```

2022-09-20 12:45 UTC, Uzlopak requested changes
I miss a test if providing a buffer actually gets the right result.

Here https://github.com/fastify/fastify-cookie/blob/e1394d0186bb86d62490b7632e0698115d4cf1c1/test/signer.test.js#L37 add something this:

```js
    t.equal(result, sign(input, Buffer.from(secret)))
    t.equal(result, sign(input, [Buffer.from(secret)]))
```

2022-09-20 12:46 UTC, Uzlopak commented on types/plugin.d.ts
> +  export type SignerFactory = (secrets: string | Array<string> | Buffer | Array<Buffer>, algorithm?: string) => SignerBase;
I guess we can use only one notation through out the types: 

```suggestion
  export type SignerFactory = (secrets: string | string[] | Buffer | Buffer[], algorithm?: string) => SignerBase;
```

2022-09-21 08:06 UTC, Uzlopak approved these changes

2022-09-25 08:03 UTC, Eomm approved these changes

2022-09-25 08:03 UTC, merged