chore: move from tap to node:test
fastify/fastify-cookie pull request #306
Opened 2024-11-05 16:17 UTC by eugleenyc

These changes are related to the issue https://github.com/fastify/fastify/issues/5555
Changed signer.test.js and cookie.test.js to use node:test instead of tap.

#### Checklist

- [x] run `npm run test`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-11-06 01:26 UTC, gurgunday approved these changes
LGTM

2024-11-07 01:52 UTC, dancastillo reviewed
Can you use [test context](https://nodejs.org/api/test.html#class-testcontext) so `assert.strictEqual` -> t.assert.strictEqual`

2024-11-07 01:52 UTC, dancastillo commented on test/cookie.test.js
Can you add back in `t.plan`. The test will end before assertions are compelete i believe
Then for the tests with callbacks update to
```js
test('test name here', (t, done) => {
  // set up and test code
  done() // call after last assertion
})

2024-11-07 11:24 UTC, jsumners requested changes
Please address @dancastillo's concern.

2024-12-08 17:17 UTC, Uzlopak commented
@jsumners 
@dancastillo 

Fixed the tests... PTAL.

2024-12-10 11:32 UTC, jsumners approved these changes
Looks good to me.

2024-12-10 12:38 UTC, gurgunday approved these changes

2024-12-10 12:38 UTC, merged